Add a 'lexer lifetime.
For the program:

  pub fn parse_my_data<'a>(input: &'a str) -> Option<&'a str> {
      let lexer_def = crate::t_l::lexerdef();
      let l = lexer_def.lexer(input);
      match crate::t_y::parse(&l) {
          (Option::Some(x),_) => Some(x),
          _ => None
      }
  }

this previously failed to compile with:

  error[E0515]: cannot return value referencing local variable `l`
    --> src/main.rs:26:32
     |
  25 |     match crate::t_y::parse(&l) {
     |                             -- `l` is borrowed here
  26 |         (Option::Some(x),_) => Some(x),
     |                                ^^^^^^^ returns a value referencing data owned by the current function

  error[E0515]: cannot return value referencing local variable `lexer_def`
    --> src/main.rs:26:32
     |
  24 |     let l = lexer_def.lexer(input);
     |             --------- `lexer_def` is borrowed here
  25 |     match crate::t_y::parse(&l) {
  26 |         (Option::Some(x),_) => Some(x),
     |                                ^^^^^^^ returns a value referencing data owned by the current function

  error: aborting due to 2 previous errors; 1 warning emitted

This commit fixes that problem, mostly through introducing a new lifetime
'lexer. There is one very tiny API change in lrlex::LexerDef from:

    pub fn lexer(&self, s: &str) -> impl Lexer<StorageT> {
        LRLexer::new(self, s)
    }

to:

    pub fn lexer<'lexer, 'input: 'lexer>(
        &'lexer self,
        s: &'input str
    ) -> LRLexer<'lexer, 'input, StorageT> {
        LRLexer::new(self, s)
    }

This is a safe change because, by definition, lrlex can only return LRLexer
instances. The alternative to this would have been to add a second lifetime
'lexer to the Lexer trait, which seems overkill.